gateway:
  namespace: gateway

issuer:
  server: https://acme-v02.api.letsencrypt.org/directory
  # email: "john@doe.com" # REQUIRED
  # accountKeySecretName: "tls-account-key" # REQUIRED

certificates:
  root:
    secretName: root-tls-cert
    # domainName: "psp.com" # REQUIRED
  auth:
    secretName: auth-tls-cert
    # domainName: "auth.psp.com" # REQUIRED
  monitoring:
    secretName: monitoring-tls-cert
    # domainName: "metrics.psp.com" # REQUIRED
  secrets:
    secretName: secrets-tls-cert
    # domainName: "secrets.psp.com" # REQUIRED

cert-manager:
  crds:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  webhook:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  cainjector:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
